// Code generated by Kitex v0.11.3. DO NOT EDIT.
package flashkill

import (
	server "github.com/cloudwego/kitex/server"
	flashkill "server/rpc/kitex_gen/FlashKill"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler flashkill.FlashKill, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler flashkill.FlashKill, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
